apiVersion: v1
kind: Service
metadata:
  name: balancing-service
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Endpoints
metadata:
  name: balancing-service
subsets:
  - addresses:
      - ip: service-dc
      - ip: service-drc
    ports:
      - port: 5000
